#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
from langchain import LLMChain
from langchain.chat_models import ChatOpenAI
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)

api_key = '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'

chat = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo-16k", max_tokens=15000, openai_api_key=api_key, request_timeout=1500)

template = "You are an expert novel reader. You understand the context of dialogues and recognise the speaker and his/her mood from the dialogues."

system_message_prompt = SystemMessagePromptTemplate.from_template(template)

human_template = "Please extract the dialogues along with the speaker name and speaker mood from the following text: \n {chnk} \n Please reply in a consistent format (dialogue in quotes followed by speaker name and mood of the speaker in brackets)."

human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)

chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

chain = LLMChain(llm=chat, prompt=chat_prompt)

# Define the chunk size and overlap
chunk_size = 5000  # Check Maximum token limit for the model used

overlap = 500  # Number of tokens for overlapping context

def extract_dialogues_from_chapter(chapter_file):
    with open(chapter_file, 'r') as file:
        chapter_text = file.read()

    # Split the chapter into overlapping chunks
    chunks = []
    start = 0
    end = chunk_size
    while start < len(chapter_text):
        chunks.append(chapter_text[start:end])
        start = end - overlap
        end = start + chunk_size
    
    dialogues = []
    for chunk in chunks:
        response = chain.run(chnk=chunk)
        dialogues.append(response)
    
    return dialogues
        
chapter_file = './Data/Glimpse_Ch1.txt'  # Provide the path to the chapter file

dialogues = extract_dialogues_from_chapter(chapter_file)

#%% POst processing the results

# # Print the extracted dialogues
# for speaker, dialogue in dialogues:
#     print(f"{speaker}: {dialogue}")
dialogue_collection_raw=[]
dialogue_collection_speakers=[]
# All reponses including the narator
for diag in dialogues:
    tmp = diag.split("\n")
    for strngs in tmp:
        dialogue_collection_raw.append(strngs)
        if "Unknown speaker" not in strngs:
            dialogue_collection_speakers.append(strngs)

# Response without narrator
# dialogue_collec = [re.sub(r'^\d{1,2}\.\s*', '', strings) for strings in dialogue_collec_Narr if "Narrator" not in strings]


    
print("Following are the dialogues including those of the Narrator also \n",dialogue_collection_raw)
# print("Following are the dialogues excluding Narrator's \n", dialogue_collec)

#%% Writing output to file

# writing file containing dialogues of Narrator also
with open('output_raw.txt', 'w') as fil:
    for line in dialogue_collection_raw:
        fil.write("%s\n" %line)

# writing file without dialogues of Narrator

with open('output_fine.txt', 'w') as fil:
    for line in dialogue_collection_speakers:
        fil.write("%s\n" %line)















#%% Output formating

